-- Lab 3 – Các hàm hệ thống & Xử lý chuỗi

-- BÀI 1: CAST & CONVERT
-- Tổng số giờ làm việc của nhân viên theo đề án (CAST)
SELECT DA.TENDEAN,
       CAST(SUM(PC.THOIGIAN) AS DECIMAL(10,2)) AS TongGio_DECIMAL,
       CAST(SUM(PC.THOIGIAN) AS VARCHAR) AS TongGio_VARCHAR
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;
GO

-- Tổng số giờ làm việc của nhân viên theo đề án (CONVERT)
SELECT DA.TENDEAN,
       CONVERT(DECIMAL(10,2), SUM(PC.THOIGIAN)) AS TongGio_DECIMAL,
       CONVERT(VARCHAR, SUM(PC.THOIGIAN)) AS TongGio_VARCHAR
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;
GO

-- Lương trung bình phòng ban (CAST)
SELECT PB.TENPHG,
       CAST(AVG(NV.LUONG) AS DECIMAL(10,2)) AS LuongTB_DECIMAL,
       CAST(AVG(NV.LUONG) AS VARCHAR) AS LuongTB_VARCHAR
FROM NHANVIEN NV
JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
GROUP BY PB.TENPHG;
GO

-- Lương trung bình phòng ban (CONVERT)
SELECT PB.TENPHG,
       CONVERT(DECIMAL(10,2), AVG(NV.LUONG)) AS LuongTB_DECIMAL,
       CONVERT(VARCHAR, AVG(NV.LUONG)) AS LuongTB_VARCHAR
FROM NHANVIEN NV
JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
GROUP BY PB.TENPHG;
GO


-- BÀI 2: HÀM TOÁN HỌC
SELECT DA.TENDEAN,
       CEILING(SUM(PC.THOIGIAN)) AS TongGio_CEIL,
       FLOOR(SUM(PC.THOIGIAN)) AS TongGio_FLOOR,
       ROUND(SUM(PC.THOIGIAN),2) AS TongGio_ROUND
FROM DEAN DA
JOIN PHANCONG PC ON DA.MADA = PC.MADA
GROUP BY DA.TENDEAN;
GO

DECLARE @LuongTB FLOAT;
SELECT @LuongTB = ROUND(AVG(LUONG),2)
FROM NHANVIEN NV
JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
WHERE PB.TENPHG = N'Nghiên cứu';

SELECT HONV, TENLOT, TENNV, LUONG
FROM NHANVIEN
WHERE LUONG > @LuongTB;
GO


-- BÀI 3: HÀM XỬ LÝ CHUỖI
-- Nhân viên có > 2 thân nhân
SELECT UPPER(NV.HONV) AS HO,
       LOWER(NV.TENLOT) AS TENLOT,
       UPPER(SUBSTRING(NV.TENNV,2,1)) + LOWER(STUFF(NV.TENNV,2,1,'')) AS TENNV,
       SUBSTRING(NV.DCHI, CHARINDEX(' ', NV.DCHI)+1, LEN(NV.DCHI)) AS DiaChi
FROM NHANVIEN NV
JOIN THANNHAN TN ON NV.MANV = TN.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV, NV.DCHI
HAVING COUNT(TN.TENTN) > 2;
GO

-- Phòng ban đông NV nhất + thay tên trưởng phòng = 'Fpoly'
SELECT TOP 1 PB.TENPHG,
       NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS TruongPhong,
       'Fpoly' AS TenThayThe
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
JOIN NHANVIEN NVC ON PB.MAPHG = NVC.PHG
GROUP BY PB.TENPHG, NV.HONV, NV.TENLOT, NV.TENNV
ORDER BY COUNT(NVC.MANV) DESC;
GO


-- BÀI 4: HÀM NGÀY THÁNG NĂM
-- Nhân viên sinh 1960-1965
SELECT * FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;
GO

-- Tuổi nhân viên
SELECT HONV, TENLOT, TENNV, YEAR(GETDATE()) - YEAR(NGSINH) AS Tuoi
FROM NHANVIEN;
GO

-- Sinh vào thứ mấy
SELECT HONV, TENLOT, TENNV, DATENAME(WEEKDAY, NGSINH) AS ThuSinh
FROM NHANVIEN;
GO

-- Thông tin trưởng phòng
SELECT PB.TENPHG,
       NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS TruongPhong,
       PB.NG_NHANCHUC,
       CONVERT(VARCHAR, PB.NG_NHANCHUC, 105) AS NgayDDMMYY
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV;
GO
