SELECT TOP 1 MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS HOTEN, LUONG FROM NHANVIEN ORDER BY LUONG DESC;

SELECT HONV, TENLOT, TENNV, LUONG FROM NHANVIEN 
WHERE LUONG > (SELECT AVG(LUONG) FROM NHANVIEN
		WHERE PHG = (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nghiên cứu'));

SELECT PB.TENPHG, COUNT(NV.MANV) AS SOLUONG FROM NHANVIEN NV JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG GROUP BY PB.TENPHG
HAVING AVG(NV.LUONG) > 30000;

SELECT PB.TENPHG, COUNT(DA.TENDEAN) AS SOLUONG FROM DEAN DA JOIN PHONGBAN PB ON DA.PHONG = PB.MAPHG GROUP BY PB.TENPHG;