SELECT MANV, HONV, TENLOT, TENNV, PHG FROM NHANVIEN WHERE PHG = 4;

SELECT MANV, HONV, TENLOT, TENNV, LUONG, PHG FROM NHANVIEN WHERE LUONG > 30000;

SELECT MANV, HONV, TENLOT, TENNV, LUONG, PHG FROM NHANVIEN WHERE (PHG = 4 AND LUONG > 25000)
	OR (PHG = 5 AND LUONG > 30000);

SELECT HONV + ' ' + TENLOT + ' ' + TENNV + ' ' AS HOTEN, DCHI FROM NHANVIEN WHERE (DCHI LIKE '%TP HCM%') OR (DCHI LIKE N'%Tp Hồ Chí Minh%');

SELECT HONV + ' ' + TENLOT + ' ' + TENNV + ' ' AS HOTEN, DCHI FROM NHANVIEN WHERE HONV LIKE 'N%';

SELECT HONV + ' ' + TENLOT + ' ' + TENNV + ' ' AS HOTEN, NGSINH, DCHI FROM NHANVIEN WHERE HONV LIKE N'%ĐINH%' AND TENLOT LIKE N'%BÁ%' AND TENNV LIKE N'%TIÊN%';